'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MLLSSettings

    '''<summary>
    '''plDisplayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDisplayType As Global.System.Web.UI.UserControl

    '''<summary>
    '''ddlDisplayTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDisplayTypes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plSeparator As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtSeparator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeparator As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plCssClass As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCssClass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plHideCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plHideCurrent As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbHideCurrent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbHideCurrent As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plAlignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAlignment As Global.System.Web.UI.UserControl

    '''<summary>
    '''ddlAlignment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAlignment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plHyperlinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plHyperlinks As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbHyperlinks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbHyperlinks As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plFlags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plFlags As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbFlags control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbFlags As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMenu As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMenu As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plMenuFlagPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMenuFlagPosition As Global.System.Web.UI.UserControl

    '''<summary>
    '''ddlMenuFlagPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMenuFlagPosition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''plDisplayLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plDisplayLabel As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbDisplayLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDisplayLabel As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plLabelCssClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plLabelCssClass As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtLabelCSSClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLabelCSSClass As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plOnlyLanguageCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plOnlyLanguageCode As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbOnlyLanguageCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOnlyLanguageCode As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plForceHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plForceHidden As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbForceHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbForceHidden As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plMapLanguages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMapLanguages As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtMapLanguages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapLanguages As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valMapLanguages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMapLanguages As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''plMapDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plMapDomains As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtMapDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMapDomains As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''valMapDomains control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents valMapDomains As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''plUseStyleSheetForSkinObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plUseStyleSheetForSkinObject As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbUseStyleSheetForSkinObject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseStyleSheetForSkinObject As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plUseFullLocaleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plUseFullLocaleCode As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbUseFullLocaleCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseFullLocaleCode As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plTableLess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plTableLess As Global.System.Web.UI.UserControl

    '''<summary>
    '''cbTableLess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbTableLess As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''plAltFlagLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAltFlagLocation As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtAltFlagLocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAltFlagLocation As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plAltImageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plAltImageType As Global.System.Web.UI.UserControl

    '''<summary>
    '''txtaltImageType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtaltImageType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''plFlagType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plFlagType As Global.System.Web.UI.UserControl

    '''<summary>
    '''drpFlagType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpFlagType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dshSkinObjectSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dshSkinObjectSettings As Global.System.Web.UI.UserControl

    '''<summary>
    '''tblSKOSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblSKOSettings As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''plGenerateType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents plGenerateType As Global.System.Web.UI.UserControl

    '''<summary>
    '''rblGenerationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblGenerationType As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''btnGenerateNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGenerateNow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtSKOAttributes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSKOAttributes As Global.System.Web.UI.WebControls.TextBox
End Class
